### ISSUE TITLE
Is the use of localstorage enough to avoid the cookie bar?

### ISSUE THREAD

**Issue by ciaoben** [pieterbeulque/anonymous-analytics#1]
From my understanding the cookie law is not so much about cookies but any form of storing data on the client machine. Am I wrong?

**Comment by pieterbeulque** [comment]
Hi @ciaoben,

The main thing that _might_ change the legal perspective is that you change the way of identifying and tracking the user from a **third party** (i.e. Google) to **first party**.

When you use default Google Analytics, it stores a cookie from their domain to identify your visitors. This gives Google the possibility to _recognize_ your visitors on _other sites_ where Google Analytics is also installed.

When you replace that Google-provided cookie with a self-generated identifier, Google cannot identify your users elsewhere on the internet. This is not legal advice, of course, and still asking for consent is probably better if you want to make sure to be compliant.

Does that make sense?
